"""Public API for snapshot reference-catalog infrastructure."""

from .adapters.reference import (
    GasparSnapshotAdapter,
    Hip2SnapshotAdapter,
    SnapshotCatalogAdapter,
    TdscSnapshotAdapter,
    V70ASnapshotAdapter,
    IrasFscSnapshotAdapter,
    IrasPscSnapshotAdapter,
    Koen10SnapshotAdapter,
    Paunzen15SnapshotAdapter,
    UbvMeansSnapshotAdapter,
    snapshot_adapter,
)
from .reference_application import (
    ReferenceApplicationResult,
    ReferenceApplicationService,
)
from .reference_definitions import (
    GASPAR_BIBCODE,
    GASPAR_CATALOG,
    GASPAR_DEFINITION,
    GASPAR_MAIN_TABLE,
    GASPAR_REFS_TABLE,
    SNAPSHOT_CATALOGS,
    V70A_BIBCODE,
    V70A_CATALOG,
    V70A_DEFINITION,
    V70A_MAIN_TABLE,
    IRAS_FSC_BIBCODE,
    IRAS_FSC_CATALOG,
    IRAS_FSC_DEFINITION,
    IRAS_FSC_MAIN_TABLE,
    IRAS_PSC_BIBCODE,
    IRAS_PSC_CATALOG,
    IRAS_PSC_DEFINITION,
    IRAS_PSC_MAIN_TABLE,
    HIP2_BIBCODE,
    HIP2_CATALOG,
    HIP2_DEFINITION,
    HIP2_MAIN_TABLE,
    TDSC_BIBCODE,
    TDSC_CATALOG,
    TDSC_DEFINITION,
    TDSC_MAIN_TABLE,
    TDSC_SUPPLEMENT_TABLE,
    UBVMEANS_BIBCODE,
    UBVMEANS_CATALOG,
    UBVMEANS_DEFINITION,
    UBVMEANS_MAIN_TABLE,
    PAUNZEN15_BIBCODE,
    PAUNZEN15_CATALOG,
    PAUNZEN15_DEFINITION,
    PAUNZEN15_MAIN_TABLE,
    KOEN10_BIBCODE,
    KOEN10_CATALOG,
    KOEN10_DEFINITION,
    KOEN10_MAIN_TABLE,
    KOEN10_JHKL_TABLE,
    RelationshipDefinition,
    SnapshotCatalogDefinition,
)
from .reference_store import (
    AstroquerySnapshotClient,
    CdsBulkSnapshotClient,
    ReferenceBase,
    ReferenceColumn,
    ReferenceAlias,
    ReferenceRelationship,
    ReferenceRow,
    ReferenceSnapshot,
    ReferenceStore,
    ReferenceTable,
    SnapshotClient,
    SnapshotResult,
)

__all__ = [name for name in globals() if not name.startswith("_")]
